name: interest_calculator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_toggle_button: ^0.0.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  animations: ^2.0.7
  pdf: ^3.10.4
  printing: ^5.12.0
  flutter_native_splash: ^2.3.5
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.4"
  
 
 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/ic_launcher.png
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#00095d"
  
  
  

 

flutter_native_splash:  
  color: "#00095d"
  image: assets/images/logoគណនាការប្រាក់-2.png
  android: true
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/1-min.png
    - assets/images/2-min.png
    - assets/images/3-min.png
    - assets/images/4-min.png
    - assets/images/5-min.png
    - assets/images/logoគណនាការប្រាក់-2.png
    - assets/images/profile.jpg
    - assets/images/ic_launcher_round.png
    - assets/images/ic_launcher.png

  fonts:
    - family: Misan
      fonts:
        - asset: assets/fonts/MISANSKHMERVF.TTF
          style: italic
    - family: Notosan
      fonts:
        - asset: assets/fonts/NOTOSANSKHMER-BOLD.TTF
          style: italic
    # - family: Hanuman
    #   fonts:
    #     - asset: assets/fonts/HANUMANB.TTF
    #       style: italic
     
